---
name: Build Images
on:
  push:
    branches:
      - 'scan'

env:
  IMAGE_NAME: cop-java-runner
  IMAGE_REPO: quay.io/ukhomeofficedigital

jobs:
  get_datetime:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.now }}

    steps:
      - id: datetime
        run: echo "::set-output name=now::$(date +%Y%m%d%H%M)"

  build:
    name: Build container images
    runs-on: ubuntu-latest
    needs: get_datetime
    strategy:
      matrix:
        java-version: ['11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build Java Runner ${{ matrix.java-version }} and export to Docker for test
        uses: docker/build-push-action@v3
        with:
          build-args: JAVA_VERSION=${{ matrix.java-version }}
          context: .
          load: true
          pull: true
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.java-version }}-jre.test

      - name: Basic sanity check of image before push
        run: docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.java-version }}-jre.test java --version

      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ matrix.java-version}}-jre.test
          artifact-name: ${{ env.IMAGE_NAME }}.${{ matrix.java-version }}-jre.sbom.spdx.json
          output-file: ${{ env.IMAGE_NAME }}.${{ matrix.java-version }}-jre.spdx.json

      - name: Scan SBOM
        uses: anchore/scan-action@v3
        id: scan
        with:
          sbom: ${{ env.IMAGE_NAME }}.${{ matrix.java-version }}-jre.spdx.json
          severity-cutoff: critical
          acs-report-enable: true

      - name: Debug
        run: ls -la

      - name: Inspect Scan SARIF file
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Upload Scan SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

    # - name: Build Java Runner ${{ matrix.java-version }} and Push to Quay
    #   uses: docker/build-push-action@v3
    #   with:
    #     build-args: JAVA_VERSION=${{ matrix.java-version }}
    #     context: .
    #     pull: true
    #     push: true
    #     tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.java-version }}-jre.${{ needs.get_datetime.outputs.datetime }}.0
