---
name: Build Images
on:
  push:
    branches:
      - 'gh-actions'

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['18', '17', '16', '11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get date and time
        id: date
        run: echo "::set-output name=datetime::$(date +%Y%m%d%H%M)"

      - name: Build Java Runner ${{ matrix.java-version }}
        uses: docker/build-push-action@v3
        with:
          build-args: JAVA_VERSION=${{ matrix.java-version }}
          context: .
          tags: cop-java-runner:${{ matrix.java-version }}.${{ steps.date.outputs.datetime }}.0,cop-java-runner:${{ matrix.java-version}}.latest
          pull: true

      - name: Sanity check
        run: |
          docker run --rm cop-java-runner:${{ matrix.java-version }}.latest java --version

      - name: Test Happy
        run:
          echo "The test passed"
