---
name: Image Build
on:
  push:
    branches:
      - 'gh-actions'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get date and time
        id: date
        run: echo "::set-output name=datetime::$(date +%Y%m%d%H%M)"

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: cop-java-runner:18.${{ steps.date.outputs.datetime }}.0,cop-java-runner:18.latest
          pull: true
